### ISSUE TITLE
Awesome-book-Project peer-to-peer-code-review

### ISSUE THREAD

**Issue by Bantealem** [dlwub/Awesome-Books#3]
# Acknowledgments
- Your code is clean and understandable.
- The semantic tag is correct.
-  No linter error.

# Issue
- Add comments to your code.

**Comment by AlierPM** [comment]
# Acknowlegment 🏆 
* Follow the best practices for HTML and Javascript

# Some issues to improve on might be:
 * It is nice to modify your project with a description this will help what your project was.
 * Adding comments in all the technical concepts help in understanding for it ease readability

**Comment by AduwuJoseph** [comment]
As already acknowledged by @Bantealem, your code looks clean and follows the semantics of both html, CSS and Javascript. However, for the purpose of code maintainability, it will be nice if sections that represent a particular action or feature and grouped using comments so as to allow anybody that might wants to maintain or improve on your code finds it easy.

Also, based on ES6 semantics, it will be nice if your JavaScript function are converted to array functions.
